spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 123
    platform: h2
    url: jdbc:h2:~/mydb1
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
