INSERT INTO GENDER_DTLS(GENDER_Id,GENDER_TXT) VALUES(1,'Male');
INSERT INTO GENDER_DTLS(GENDER_Id,GENDER_TXT) VALUES(2,'Fe-Male');
INSERT INTO COURSE_DTLS(COURSE_ID,COURSE_NAME) VALUES(101,'Java');
INSERT INTO COURSE_DTLS(COURSE_ID,COURSE_NAME) VALUES(102,'Python');
INSERT INTO COURSE_DTLS(COURSE_ID,COURSE_NAME) VALUES(103,'Angular 10');
INSERT INTO COURSE_TIMINGS_DTLS(TIMING_ID,TIMING)VALUES(201,'Morning');
INSERT INTO COURSE_TIMINGS_DTLS(TIMING_ID,TIMING) VALUES(202,'Afternoon');
INSERT INTO COURSE_TIMINGS_DTLS(TIMING_ID,TIMING) VALUES(203,'Evening');
